name: my_business_card
description: My Business Card Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
          style: italic
    - family: Mooli
      fonts:
        - asset: fonts/Mooli-Regular.ttf